failing test case - reason bad implementation of withTitle + table_alias
atk4/data pull request #784
Opened 2020-11-19 22:09 UTC by DarkSide666

2020-12-08 14:13 UTC, georgehristov commented
The issue is on this line:
https://github.com/atk4/data/blob/7a39b627c32715a81abfaa94101d994c5c269b18/src/Reference/HasOneSql.php#L54

Model::refLink is used which adds aliases but in DSQL the operations apart from SELECT use template `[table_noalias]`

2020-12-09 13:55 UTC, DarkSide666 commented
Maybe we should have a way to tell refLink to not add aliases in some specific cases?

2021-11-10 14:17 UTC, mvorisek commented
with the latest data (https://github.com/atk4/data/commit/f7805b6ed2f8d3e7345bee30238a4d0a06c59f6b) the test is passing without any change needed

2021-11-10 14:22 UTC, mvorisek commented on tests/ReferenceSqlTest.php
> +        // var_dump($ord->action('update')->getDebugQuery()); // update "order" set "name"='CCC'  where "oo"."id" = 3 which is wrong
```
update
  "order"
set
where
  "oo"."owner_id" in (
    select
      "id"
    from
      "user" "uu"
  )
```

is now dumped/queried

2021-11-23 01:12 UTC, mvorisek requested changes
I am still not convinced by fixing this issue for Field specificly and for condition only as proposed by @samsouthardjr . However the fix fixes also this usecase.

2021-11-28 13:31 UTC, mvorisek commented
closing in favor of proper fix in https://github.com/atk4/data/pull/938 incl. test

2021-11-28 13:31 UTC, closed without merging